use_frameworks!

platform :ios, '8.0'

target 'ZSWeexPluginLoader_Example' do
  pod 'ZSWeexPluginLoader', :path => '../'

  target 'ZSWeexPluginLoader_Tests' do
    inherit! :search_paths

    
  end
end
